# (C) Copyright Hewlett Packard Enterprise Development LP
apiVersion: tapms.hpe.com/v1alpha1
kind: Tenant
metadata:
  labels:
  name: example-tenant-2
  namespace: tenants
spec:
  tenantname: ExampleTenant2
  childnamespaces:
    - "child-ns1-v1alpha1"
    - "child-ns2-v1alpha1"
  tenantresources:
    - type: "ExampleResourceTypeV1Alpha1"
      enforceexclusivehsmgroups: true
      xnames:
        - "xname-2"
      hsmgrouplabel: "ExampleLabelV1Alpha1"
      hsmpartitionname: "ExamplePartitionV1alpha1"