# (C) Copyright Hewlett Packard Enterprise Development LP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sshot-net-operator-role
rules:
- apiGroups:
  - slingshot.hpe.com
  resources:
  - slingshottenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slingshot.hpe.com
  resources:
  - slingshottenants/status
  verbs:
  - get
- apiGroups:
  - tapms.hpe.com
  resources:
  - tenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tapms.hpe.com
  resources:
  - tenants/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - list
  - watch
  - get



