//go:build !ignore_autogenerated

/*
(C) Copyright Hewlett Packard Enterprise Development LP
*/


// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlingshotTenant) DeepCopyInto(out *SlingshotTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlingshotTenant.
func (in *SlingshotTenant) DeepCopy() *SlingshotTenant {
	if in == nil {
		return nil
	}
	out := new(SlingshotTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlingshotTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlingshotTenantList) DeepCopyInto(out *SlingshotTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlingshotTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlingshotTenantList.
func (in *SlingshotTenantList) DeepCopy() *SlingshotTenantList {
	if in == nil {
		return nil
	}
	out := new(SlingshotTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlingshotTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlingshotTenantSpec) DeepCopyInto(out *SlingshotTenantSpec) {
	*out = *in
	in.VNIPartition.DeepCopyInto(&out.VNIPartition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlingshotTenantSpec.
func (in *SlingshotTenantSpec) DeepCopy() *SlingshotTenantSpec {
	if in == nil {
		return nil
	}
	out := new(SlingshotTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlingshotTenantStatus) DeepCopyInto(out *SlingshotTenantStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlingshotTenantStatus.
func (in *SlingshotTenantStatus) DeepCopy() *SlingshotTenantStatus {
	if in == nil {
		return nil
	}
	out := new(SlingshotTenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VNIPartition) DeepCopyInto(out *VNIPartition) {
	*out = *in
	if in.VNIRange != nil {
		in, out := &in.VNIRange, &out.VNIRange
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EdgePortDFA != nil {
		in, out := &in.EdgePortDFA, &out.EdgePortDFA
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VNIPartition.
func (in *VNIPartition) DeepCopy() *VNIPartition {
	if in == nil {
		return nil
	}
	out := new(VNIPartition)
	in.DeepCopyInto(out)
	return out
}
