# (C) Copyright Hewlett Packard Enterprise Development LP
# permissions for end users to view slingshottenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: slingshottenant-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sshot-net-operator
    app.kubernetes.io/part-of: sshot-net-operator
    app.kubernetes.io/managed-by: kustomize
  name: slingshottenant-viewer-role
rules:
- apiGroups:
  - slingshot.hpe.com
  resources:
  - slingshottenants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - slingshot.hpe.com
  resources:
  - slingshottenants/status
  verbs:
  - get
