---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.Values.clusterRole.name}}
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service}}
  annotations:
    meta.helm.sh/release-name: {{.Release.Name}}
    meta.helm.sh/release-namespace: {{.Release.Namespace}}
rules:
- apiGroups: ["slingshot.hpe.com", "tapms.hpe.com"]
  resources: ["slingshottenants", "tenants"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["slingshot.hpe.com", "tapms.hpe.com"]
  resources: ["slingshottenants/status", "tenants/status"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["list", "watch"]

