apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.serviceAccount.name}}
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service}}
  annotations:
    meta.helm.sh/release-name: {{.Release.Name}}
    meta.helm.sh/release-namespace: {{.Release.Namespace}}
