# (C) Copyright Hewlett Packard Enterprise Development LP
apiVersion: slingshot.hpe.com/v1alpha1
kind: SlingshotTenant
metadata:
  name: slingshottenant-example3
  namespace: slingshot-tenants
spec:
  tenantname: example-tenant-v1alpha3
  vnipartition:
    vniCount: 10000

